language: c

matrix:
  include:
    - os: linux
      dist: xenial
      compiler:
        - gcc
        - clang
      addons:
        apt:
          update: true
          packages:
            - build-essential
            - qtdeclarative5-dev
            - 'g++-9'
            - 'clang-8'

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi

script:
  - qmake -qt=qt5 --version
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - qmake -qt=qt5 config+="release" ../lcsniff.pro
  - make -j
