language: c

dist:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - build-essential
      - qtdeclarative5-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi

script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - qmake config+="release" ../lcsniff.pro
  - make -j
